export const CREATE_QUIZ = "CREATE_QUIZ"
export const UPDATE_QUIZ = "UPDATE_QUIZ"
export const LIKE_QUIZ = "LIKE_QUIZ"
export const DELETE_QUIZ = "DELETE_QUIZ"
export const FETCH_QUIZ = "FETCH_QUIZ"
export const FETCH_ALL_QUIZES = "FETCH_ALL_QUIZES"
export const FETCH_PUBLIC_QUIZES = "FETCH_PUBLIC_QUIZES"
export const FETCH_TEACHER_QUIZES = "FETCH_TEACHER_QUIZES"
export const FETCH_QUIZES_BY_SEARCH = "FETCH_QUIZES_BY_SEARCH"
export const COMMENT_QUIZ = "COMMENT_QUIZ"

export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"

export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const FETCH_ALL_USERS = "FETCH_ALL_USERS"

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
